@HostAddress = http://localhost:5111

### Get contact by Id

GET {{HostAddress}}/api/v1/contacts/dc421216-5672-489f-9e5d-1692c8d1d4be
Accept: application/json


### Create contact

POST {{HostAddress}}/api/v1/contacts
Content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "jdoe@gmail.com",
    "phoneNumber": "091212121212"
}
