@HostAddress = http://localhost:5111

GET {{HostAddress}}/
Accept: application/json

### Create contact

POST {{HostAddress}}/api/v1/contacts
Content-type: application/json

{
    "firstName": "",
    "lastName": "a",
    "email": "jdoe3@gmail.com",
    "phoneNumber": "091212121212"
}
